<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	  <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
	  <NoWarn>NU1901;NU1902;NU1903;NU1904</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ClosedXML" Version="0.105.0" />
    <PackageReference Include="EPPlus" Version="8.5.4" />
    <PackageReference Include="MailKit" Version="4.14.1" />
    <PackageReference Include="Microsoft.AspNetCore.Hosting" Version="2.3.0" />
    <PackageReference Include="Microsoft.AspNetCore.Identity" Version="2.3.1" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Common" Version="10.0.7" />
    <PackageReference Include="Microsoft.Extensions.Localization" Version="10.0.1" />
    <PackageReference Include="MimeKit" Version="4.14.0" />
    <PackageReference Include="QuestPDF" Version="2025.12.3" />
    <PackageReference Include="SkiaSharp" Version="3.119.2" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.15.0" />
  </ItemGroup>



  <ItemGroup>
    <ProjectReference Include="..\Byohar.Application\Byohar.Application.csproj" />
    <ProjectReference Include="..\Byohar.Domain\Byohar.Domain.csproj" />
    <ProjectReference Include="..\Byohar.Persistance\Byohar.Persistance.csproj" />
    <ProjectReference Include="..\Byohar.Shared\Byohar.Shared.csproj" />
  </ItemGroup>
</Project>

