<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
	  <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
	  <NoWarn>NU1901;NU1902;NU1903;NU1904</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="16.1.1" />
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="MediatR" Version="12.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.3.0" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Features" Version="5.0.17" />
   <PackageReference Include="MediatR.Extensions.Microsoft.DependencyInjection" Version="11.0.0" />
	  <PackageReference Include="Microsoft.AspNetCore.SignalR.Core" Version="1.1.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.1" />
    <PackageReference Include="Microsoft.Extensions.Localization" Version="10.0.1" />
    <PackageReference Include="System.DirectoryServices.AccountManagement" Version="10.0.7" />
    <PackageReference Include="System.Reactive" Version="6.1.0" />
  </ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Byohar.Domain\Byohar.Domain.csproj" />
		<ProjectReference Include="..\Byohar.Shared\Byohar.Shared.csproj" />
	</ItemGroup>
	<ItemGroup>
		<Folder Include="Validators\Building\" />
	</ItemGroup>

</Project>
  



	